FUZZER_LOG_LEVEL=TRACE

FUZZER_REDIS_HOST=localhost
FUZZER_REDIS_PORT=6379
FUZZER_BROKER_NAME=jdozer:fuzzer:broker

FUZZER_ENGINE_HOST=fuzzer-engine
FUZZER_ENGINE_PORT=8080

FUZZER_SEEDER_HOST=fuzzer-seeder
FUZZER_SEEDER_PORT=8080

FUZZER_BACKEND_HOST=fuzzer-backend
FUZZER_BACKEND_PORT=8080

FUZZER_FRONTEND_HOST=fuzzer-frontend
FUZZER_FRONTEND_PORT=8080

FUZZER_PUSHGATEWAY_HOST=fuzzer-pushgateway
FUZZER_PUSHGATEWAY_PORT=9091

FUZZER_VECTORS_HOST=fuzzer-vectors
FUZZER_VECTORS_PORT=8080

FUZZER_PROCESSOR_HOST=fuzzer-processor
FUZZER_PROCESSOR_PORT=8080


