#
FUZZER_LOG_LEVEL=TRACE
#
FUZZER_REDIS_HOST=localhost
FUZZER_REDIS_PORT=6379
FUZZER_BROKER_NAME=jdozer:fuzzer:broker
#
FUZZER_ENGINE_HOST=localhost
FUZZER_ENGINE_PORT=9084
#
FUZZER_SEEDER_HOST=localhost
FUZZER_SEEDER_PORT=9082
FUZZER_SEEDER_CHANNEL=fuzzer:seeder
#
FUZZER_BACKEND_HOST=localhost
FUZZER_BACKEND_PORT=9081
#
FUZZER_FRONTEND_HOST=localhost
FUZZER_FRONTEND_PORT=9080
#
FUZZER_PUSHGATEWAY_HOST=localhost
FUZZER_PUSHGATEWAY_PORT=9091
#
FUZZER_VECTORS_HOST=localhost
FUZZER_VECTORS_PORT=9083
FUZZER_VECTORS_CHANNEL=fuzzer:vectors
#
FUZZER_PROCESSOR_HOST=localhost
FUZZER_PROCESSOR_PORT=9085

FUZZER_GUI_PORT=8082

NODE_OPTIONS=--disable-warning=DEP0174